version: '3.8'

services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "${XRAY_VLESS_PORT}:${XRAY_VLESS_PORT}"  # VLESS + XTLS
      - "${XRAY_WS_PORT}:${XRAY_WS_PORT}"  # WebSocket
      - "${XRAY_GRPC_PORT}:${XRAY_GRPC_PORT}"  # gRPC
    volumes:
      - ./xray/config:/etc/xray
      - ./xray/data:/var/lib/xray
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
    networks:
      - proxy-network
      - xray-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/ssl:/etc/nginx/ssl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network

  letsencrypt-companion:
    image: nginxproxy/acme-companion:latest
    container_name: letsencrypt-companion
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/ssl:/etc/nginx/ssl
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network

  admin-panel:
    image: node:18-alpine
    container_name: xray-admin
    restart: unless-stopped
    volumes:
      - ./admin-panel:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - VIRTUAL_HOST=${ADMIN_DOMAIN}
      - LETSENCRYPT_HOST=${ADMIN_DOMAIN}
      - PORT=${ADMIN_PANEL_PORT}
    networks:
      - proxy-network
      - xray-network

networks:
  proxy-network:
    driver: bridge
  xray-network:
    driver: bridge 