services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "${XRAY_VLESS_PORT}:${XRAY_VLESS_PORT}"  # VLESS + XTLS
      - "${XRAY_WS_PORT}:${XRAY_WS_PORT}"  # WebSocket
      - "${XRAY_GRPC_PORT}:${XRAY_GRPC_PORT}"  # gRPC
    volumes:
      - ./xray/config:/etc/xray
      - ./xray/data:/var/lib/xray
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
    networks:
      - proxy-network
      - xray-network
    depends_on:
      - nginx-proxy
      - letsencrypt-companion

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network
    labels:
      - "com.github.nginx-proxy.nginx"

  letsencrypt-companion:
    image: nginxproxy/acme-companion:latest
    container_name: letsencrypt-companion
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network

  admin-panel:
    image: node:18-alpine
    container_name: xray-admin
    restart: unless-stopped
    volumes:
      - ./admin-panel:/app
      - ./admin-panel/data:/app/data
    working_dir: /app
    command: sh -c "mkdir -p /app/data && npm install && npm start"
    environment:
      - VIRTUAL_HOST=${ADMIN_DOMAIN}
      - LETSENCRYPT_HOST=${ADMIN_DOMAIN}
      - VIRTUAL_PORT=3000
      - PORT=3000
    networks:
      - proxy-network
      - xray-network
    depends_on:
      - nginx-proxy
      - letsencrypt-companion

networks:
  proxy-network:
    driver: bridge
  xray-network:
    driver: bridge 